# Contact E-Mail (Public!)
email: "ethericall.help@gmail.com"

# Github (Not link, only name or org.)
# github: "Ethericall-Studio" Bo Gorol nie chce zak≈Çadki GitHub :D

# Site name and main title
name: "Ethericall Studio"
title: "Ethericall Studio"

# Site version
version: "v1.1.1"

# Site Description
description: "Ethericall official website"

# Discord server invite
discord: "https://discord.gg/wyfzxHA"
# Theme of Discord widget
discord-theme: "dark"
# Discord support server ID
discord-id: "623945078506782762"

# Google tracking id
# tracking_id: "UA-"

# Google site verification
# verivication: "456dsvhbwhygjud"

# Twitter
twitter: "@ethericall"
# Facebook
facebook: "https://www.facebook.com/Ethericall-646380125823095/"
# Instagram
instagram: "ethericall.studio"
# Site base-url (no slash at end, not link!)
baseurl: ""

# Site url (link or dir eg. "/site" or "https://igorkowalczyk.github.io
url: "https://ethericall.com"
