# Contact E-Mail (Public!)
email: "ethericall.help@gmail.com"

# Github (Not link, only name or org.)
# github: "Ethericall-Studio" Bo Gorol nie chce zakładki GitHub :D

# Site name and main title
name: "Ethericall Studio"
title: "Ethericall Studio"

# Site version
version: "v1.1.1"

# Site Description
description: "Ethericall official website"

# Discord server invite
discord: "https://discord.gg/bpCUUNn"
# Theme of Discord widget
discord-theme: "dark"
# Discord support server ID
discord-id: "737997850662666312"

# Google tracking id
# tracking_id: "UA-"

# Google site verification
# verivication: "456dsvhbwhygjud"

# Site info banner
banner:
 enabled: "true"
 text: "We're currently recruting for work (3D/2D Graphic, C# / Unity)."
 text-pl: "Mamy wolne miejsca pracy (Grafik 3D/2D, C# / Unity)."
 # link: "jobs"
 # link-pl: "jobs-pl"
 link: "contact"
 link-pl: "contact-pl"
 link-text: "Contact us →"
 link-text-pl: "Napisz do nas →"

# Twitter
twitter: "@ethericall"
# Facebook
facebook: "https://www.facebook.com/Ethericall-646380125823095/"
# Instagram
instagram: "ethericall.studio"
# Site base-url (no slash at end, not link!)
baseurl: ""

# Site url (link or dir eg. "/site" or "https://igorkowalczyk.github.io
url: "https://ethericall.com"
